# version: '3.8'
services:
  backend:
    build: ./navyaraga-ui
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

  frontend:
    build: ./palmonas-reimagined-react
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
